development:
  RIDEPILOT_HOST:
  SYSTEM_ADMIN_EMAIL:
  SYSTEM_ADMIN_PASSWORD:
  SYSTEM_SEND_FROM_ADDRESS:
  OPEN_TRIP_PLANNER_URL:
  GOOGLE_API_KEY:

test:
  RIDEPILOT_HOST:
  SYSTEM_SEND_FROM_ADDRESS:
  OPEN_TRIP_PLANNER_URL:

production:   
  RIDEPILOT_HOST:     
  SYSTEM_ADMIN_EMAIL:    
  SYSTEM_ADMIN_PASSWORD: 
  SMTP_MAIL_ADDR:                 
  SMTP_MAIL_DOMAIN:               
  SMTP_MAIL_PASSWORD:             
  SMTP_MAIL_PORT:                 
  SMTP_MAIL_USER_NAME:            
  SYSTEM_SEND_FROM_ADDRESS:       
  OPEN_TRIP_PLANNER_URL:            
  GOOGLE_API_KEY:
