development:
  secret_key_base: d2531ead0d33d1f71b616b668e898a4a40db53671f1c6e1b28481f772d7a27ebe7910b247d20865dbe5519af342eed63b9563544e5185680c7f1a3a3ed6dbe39
  ride_connection_admin_email: "admin@rideconnection.org"
  ride_connection_admin_password: "password1!"

test:
  secret_key_base: 1760e5c042b5e388233a98c36be43ec94efb58baf8bae9046dff6a79c698e76e2269ca0749f899771b3fc754aeaecda6ad30d1621c6d05a9a2579be15056eb54
  ride_connection_admin_email: "admin@rideconnection.org"
  ride_connection_admin_password: "password1!"

integration:
  secret_key_base:                <%= ENV["SECRET_KEY_BASE"] %>
  ride_connection_admin_email:    <%= ENV["RIDE_CONNECTION_ADMIN_EMAIL"] %>
  ride_connection_admin_password: <%= ENV["RIDE_CONNECTION_ADMIN_PASSWORD"] %>

qa:
  secret_key_base:                <%= ENV["SECRET_KEY_BASE"] %>
  ride_connection_admin_email:    <%= ENV["RIDE_CONNECTION_ADMIN_EMAIL"] %>
  ride_connection_admin_password: <%= ENV["RIDE_CONNECTION_ADMIN_PASSWORD"] %>

production:
  secret_key_base:                <%= ENV["SECRET_KEY_BASE"] %>
  ride_connection_admin_email:    <%= ENV["RIDE_CONNECTION_ADMIN_EMAIL"] %>
  ride_connection_admin_password: <%= ENV["RIDE_CONNECTION_ADMIN_PASSWORD"] %>